### ISSUE TITLE
Sierra alignment result not match with consensus sequence

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/sierra-sars2#9]
GISAID sequence: EPI_ISL_6795834
Variants: BA.2
Gene and position: Spike pos 24S or 27S

The consensus file is using 24S, the alignment program is using 27S.

<img width="679" alt="Screen Shot 2022-04-07 at 10 23 26 AM" src="https://user-images.githubusercontent.com/988193/162330235-cb7afc52-cc87-4586-afb7-d3b30bc6d849.png">

**Comment by philiptzou** [comment]
Detail: A27S got a bonus score +1 and L24S got a penalty score -2. Therefore a +3 bonus score for 25-27del will offset the -2 and +1 scoring change. A +4 bonus score will push 25-27del to the best placement.

**Comment by philiptzou** [comment]
> @philiptzou if we use the sierra mutation list, how to resolve the conflict between sierra mutation list and outbreak.info sync result in covid-drdb-payload database? Otherwise it will cause confusion.

Just keep post conflicts you found to this repository. We have a scoring system designing for resolve such issue and we should add more rules if our results are conflict to Outbreak.info.

We can also develop post-import constraint for checking such discrepancies.
